name: Maven Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 20
        uses: actions/setup-java@v2
        with:
          java-version: 20
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn package

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-artifact
          path: target/*.jar
